=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/jsonschema/did.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "did",
  "title": "Battery-Ecosystem DID Document",
  "description": "Minimal on-chain DID record with a revocation tag.",
  "type": "object",
  "required": ["@context", "id", "verificationMethod", "timestamp", "revoked"],
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "enum": [
          "https://www.w3.org/2018/credentials/v1",
          "http://localhost:8443/docs/did.schema.html"
        ]
      },
      "minItems": 2,
      "maxItems": 2,
      "uniqueItems": true
    },
    "id": { "$ref": "common.defs.schema.json#/definitions/DID" },
    "verificationMethod": { "$ref": "#/definitions/verificationMethod" },
    "service": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/BatterypassApiService" },
          { "$ref": "#/definitions/HandleDidService" }
        ]
      }
    },
    "timestamp": { "$ref": "common.defs.schema.json#/definitions/DateTime" },
    "revoked": {
      "type": "boolean",
      "description" : "A revoked flag indicating if an DID is no longer valid."
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "id": { "pattern": "^did:batterypass:bms" }
        }
      },
      "then": {
        "required": ["service"],
        "properties": {
          "service": {
            "items": { "$ref": "#/definitions/BatterypassApiService" },
            "minItems": 1
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "id": {
            "pattern": "^did:batterypass:cloud"
          }
        }
      },
      "then": {
        "required": ["service"],
        "properties": {
          "service": {
            "items": {
              "$ref": "#/definitions/BatterypassApiService"
            },
            "minItems": 1,
            "maxItems": 1
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "id": { "pattern": "^did:batterypass:(eu|oem)" }
        }
      },
      "then": {
        "required": ["service"],
        "properties": {
          "service": {
            "items": { "$ref": "#/definitions/HandleDidService" },
            "minItems": 1,
            "maxItems": 1
          }
        }
      }
    }
  ],
  "definitions": {
    "verificationMethod": {
      "type": "object",
      "required": ["id", "type", "controller", "publicKeyMultibase"],
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string" },
        "type": { "type": "string" },
        "controller": { "type": "string" },
        "publicKeyMultibase": { "type": "string" }
      }
    },
    "BatterypassApiService": {
      "type": "object",
      "required": ["id", "type", "serviceEndpoint"],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^did:batterypass:(bms|cloud):[A-Za-z0-9._-]+#batterypassApi(-[a-zA-Z0-9._-]+)?"
        },
        "type": { "const": "BatteryPassAPI" },
        "serviceEndpoint": { "type": "string" }
      }
    },
    "HandleDidService": {
      "type": "object",
      "required": ["id", "type", "serviceEndpoint"],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^did:batterypass:(oem|eu):[A-Za-z0-9._-]+#handleDid$"
        },
        "type": { "const": "HandleDID" },
        "serviceEndpoint": { "type": "string" }
      }
    }
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/docs/VC-DID-examples/service.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/did.schema.html"
  ],
  "id": "did:batterypass:service.tuv-sued-42",
  "verificationMethod": {
    "id": "did:batterypass:service.tuv-sued-42#key-1",
    "type": "JsonWebKey2020",
    "controller": "did:batterypass.eu",
    "publicKeyMultibase": "z6MkqhF8pbUxQmyFzZzd2Mo7nBfEY4PjwJa1bv9vJf1WZ58G"
  },
  "timestamp": "2025-04-04T07:30:00Z",
  "revoked": false
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/docs/VC-DID-examples/cloud.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/did.schema.html"
  ],
  "id": "did:batterypass:cloud.vw-node-eu-central",
  "verificationMethod": {
    "id": "did:batterypass:cloud.vw-node-eu-central#key-1",
    "type": "JsonWebKey2020",
    "controller": "did:batterypass:oem.VW",
    "publicKeyMultibase": "z6MkqZgLvANEVv5ubbo8t7MX8fYVhXVDpfjE4a2PkLMnB1sU"
  },
  "service": [
    {
      "id": "did:batterypass:cloud.vw-node-eu-central#batterypassApi",
      "type": "BatteryPassAPI",
      "serviceEndpoint": "https://<cloud-endpoint>"
    }
  ],
  "timestamp": "2025-04-02T09:00:00Z",
  "revoked": false
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/core/trustanchor.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/did.schema.html"
  ],
  "id": "did:batterypass:eu",
  "verificationMethod": {
    "id": "did:batterypass:eu#key-1",
    "type": "JsonWebKey2020",
    "controller": "did:batterypass:eu",
    "publicKeyMultibase": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQrlJgSc0Idu6NJz8sBnuWtBFePqmRUxO8thHlQn4yp+JFaGChLxcO9yEs90Edu7+ShMDON3FRdQmh/tx0y6dvQ==\n-----END PUBLIC KEY-----"
  },
  "timestamp": "2006-01-02T15:04:05Z",
  "revoked": false
}

=== THI-CSI/decentralized_iam_battery_data/mock_bms/testing/testEndpointBlockchain/cloud.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/did.schema.html"
  ],
  "id": "did:batterypass:cloud.vw-node-eu-central",
  "verificationMethod": {
    "id": "did:batterypass:cloud.vw-node-eu-central#key-1",
    "type": "JsonWebKey2020",
    "controller": "did:batterypass:oem.VW",
    "publicKeyMultibase": "BKmR7J6FQnmfHjNoKGB7qICAUB/Mlda3TnQff7g5RPeScA3ePsoFXTnosvQAgQdg0eOnivX5MyEf+3T85O7xHsE="
  },
  "service": [
    {
      "id": "did:batterypass:cloud.vw-node-eu-central",
      "type": "BatteryPassAPI",
      "serviceEndpoint": "https://<cloud-endpoint>"
    }
  ],
  "timestamp": "2025-04-02T09:00:00Z",
  "revoked": false
}
