=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/jsonschema/vc.bmsProduced.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "vc.bmsProduction",
  "title": "BMS Production Verifiable Credential",
  "description": "Schema for verifying BMS Production claims.",
  "type": "object",
  "required": ["@context", "id", "type", "issuer", "holder", "issuanceDate", "expirationDate", "credentialSubject", "proof"],
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "enum": [
          "https://www.w3.org/2018/credentials/v1",
          "http://localhost:8443/docs/vc.bmsProduction.schema.html"
        ]
      },
      "minItems": 2,
      "maxItems": 2,
      "uniqueItems": true,
      "description": "Defines the JSON-LD context, providing meaning to terms used in the credential."
    },
    "id": { "type": "string", "format": "uri" },
    "type": {
      "type": "array",
      "minItems": 2,
      "items": { "type": "string" },
      "prefixItems": [
        { "const": "VerifiableCredential" },
        { "const": "BMSProduction" }
      ],
      "uniqueItems": true,
      "maxItems": 2
    },
    "issuer": { "$ref": "common.defs.schema.json#/definitions/DID" },
    "holder": { "$ref": "common.defs.schema.json#/definitions/DID" },
    "issuanceDate": { "$ref": "common.defs.schema.json#/definitions/DateTime" },
    "expirationDate": { "$ref": "common.defs.schema.json#/definitions/DateTime" },
    "credentialSubject": {
      "type": "object",
      "required": ["id", "type", "bmsDid", "timestamp", "lotNumber"],
      "additionalProperties": false,
      "properties": {
        "id": { "$ref": "common.defs.schema.json#/definitions/URI" },
        "type": {
          "type": "string",
          "const": "BMSProduction"
        },
        "bmsDid": { "$ref": "common.defs.schema.json#/definitions/DID" },
        "timestamp": { "$ref": "common.defs.schema.json#/definitions/DateTime" },
        "lotNumber": { "type": "string" }
      }
    },
    "proof": { "$ref": "common.defs.schema.json#/definitions/Proof" }
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/docs/test-examples/oem-vc.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vc.bmsProduction.schema.html"
  ],
  "id": "urn:uuid:982c43ee-3d16-419a-a2f4-5c61710f428b",
  "type": [
    "VerifiableCredential",
    "BMSProduction"
  ],
  "issuer": "did:batterypass:bms.test",
  "holder": "did:batterypass:oem.VW",
  "issuanceDate": "2025-06-10T12:01:00Z",
  "expirationDate": "2026-06-10T12:01:00Z",
  "credentialSubject": {
    "id": "did:batterypass:oem.VW",
    "type": "BMSProduction",
    "bmsDid": "did:batterypass:bms.test",
    "timestamp": "2025-06-10",
    "lotNumber": "LOT-775533"
  },
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-06-10T12:01:03Z",
    "verificationMethod": "did:batterypass:oem.VW#key-1",
    "proofPurpose": "authentication",
    "jws": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHA6Ly9sb2NhbGhvc3Q6ODQ0My9kb2NzL3ZjLmJtc1Byb2R1Y3Rpb24uc2NoZW1hLmh0bWwiXSwiaWQiOiJ1cm46dXVpZDo5ODJjNDNlZS0zZDE2LTQxOWEtYTJmNC01YzYxNzEwZjQyOGIiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiQk1TUHJvZHVjdGlvbiJdLCJpc3N1ZXIiOiJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnRlc3QiLCJob2xkZXIiOiJkaWQ6YmF0dGVyeXBhc3M6b2VtLlZXIiwiaXNzdWFuY2VEYXRlIjoiMjAyNS0wNi0xMFQxMjowMTowMFoiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDYtMTBUMTI6MDE6MDBaIiwiY3JlZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6YmF0dGVyeXBhc3M6b2VtLlZXIiwidHlwZSI6IkJNU1Byb2R1Y3Rpb24iLCJibXNEaWQiOiJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnRlc3QiLCJ0aW1lc3RhbXAiOiIyMDI1LTA2LTEwIiwibG90TnVtYmVyIjoiTE9ULTc3NTUzMyJ9LCJwcm9vZiI6eyJ0eXBlIjoiRWNkc2FTZWNwMjU2cjFTaWduYXR1cmUyMDE5IiwiY3JlYXRlZCI6IjIwMjUtMDYtMTBUMTI6MDE6MDNaIiwidmVyaWZpY2F0aW9uTWV0aG9kIjoiZGlkOmJhdHRlcnlwYXNzOm9lbS5WVyNrZXktMSIsInByb29mUHVycG9zZSI6ImF1dGhlbnRpY2F0aW9uIiwiandzIjoiIn19.Y0_Rv4kr2CiVWLaotOkMUs5b7Lop5pGfGufEyyyWbKtmLpviFBqrOLFBj2IiYF0wykpsAcZTDG94xc82WCgOptAZ2FN4oFUuy82xuZbjzHgfqNUXBpvis9FDLI1MvaVPC7X9uux31LXjh70RPkUciJSW18eQkkvyDnJZitD-F6xSo1913Dvzj9XeIW5kJiagrHIrnuHIflfubdbvBqNsrZlueWwSvSbEzqgEx18hEilbuVOlOtKMERNMENNPguMigLplSl8rnNdIHFNHboCXIkt2u3RHepaeUHw86U-GhLnC6ExNazyMgf5-Wsr1jRwtmPLgoZEcQmLk1ickT2ywlw"
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/api/web/jsonexample/requests/request.vc.create.1.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vc.bmsProduction.schema.html"
  ],
  "id": "urn:uuid:982c43ee-3d16-419a-a2f4-5c61710f428b",
  "type": [
    "VerifiableCredential",
    "BMSProduction"
  ],
  "issuer": "did:batterypass:bms.sn-544b51e7",
  "holder": "did:batterypass:oem.VW",
  "issuanceDate": "2025-06-10T12:01:00Z",
  "expirationDate": "2026-06-10T12:01:00Z",
  "credentialSubject": {
    "id": "did:batterypass:oem.VW",
    "type": "BMSProduction",
    "bmsDid": "did:batterypass:bms.sn-544b51e7",
    "timestamp": "2025-06-10T12:01:00Z",
    "lotNumber": "LOT-775533"
  },
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-06-10T12:01:03Z",
    "verificationMethod": "did:batterypass:bms.sn-544b51e7#key-1",
    "proofPurpose": "authentication",
    "jws": "eyJhbGciOiJFUzI1NiJ9.eyJAY29udGV4dCI6IFsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCAiaHR0cDovL2xvY2FsaG9zdDo4NDQzL2RvY3MvdmMuYm1zUHJvZHVjdGlvbi5zY2hlbWEuaHRtbCJdLCAiaWQiOiAidXJuOnV1aWQ6OTgyYzQzZWUtM2QxNi00MTlhLWEyZjQtNWM2MTcxMGY0MjhiIiwgInR5cGUiOiBbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwgIkJNU1Byb2R1Y3Rpb24iXSwgImlzc3VlciI6ICJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnNuLTU0NGI1MWU3IiwgImhvbGRlciI6ICJkaWQ6YmF0dGVyeXBhc3M6b2VtLlZXIiwgImlzc3VhbmNlRGF0ZSI6ICIyMDI1LTA2LTEwVDEyOjAxOjAwWiIsICJleHBpcmF0aW9uRGF0ZSI6ICIyMDI2LTA2LTEwVDEyOjAxOjAwWiIsICJjcmVkZW50aWFsU3ViamVjdCI6IHsiaWQiOiAiZGlkOmJhdHRlcnlwYXNzOm9lbS5WVyIsICJ0eXBlIjogIkJNU1Byb2R1Y3Rpb24iLCAiYm1zRGlkIjogImRpZDpiYXR0ZXJ5cGFzczpibXMuc24tNTQ0YjUxZTciLCAidGltZXN0YW1wIjogIjIwMjUtMDYtMTBUMTI6MDE6MDBaIiwgImxvdE51bWJlciI6ICJMT1QtNzc1NTMzIn0sICJwcm9vZiI6IHsidHlwZSI6ICJFY2RzYVNlY3AyNTZyMVNpZ25hdHVyZTIwMTkiLCAiY3JlYXRlZCI6ICIyMDI1LTA2LTEwVDEyOjAxOjAzWiIsICJ2ZXJpZmljYXRpb25NZXRob2QiOiAiZGlkOmJhdHRlcnlwYXNzOmJtcy5zbi01NDRiNTFlNyNrZXktMSIsICJwcm9vZlB1cnBvc2UiOiAiYXV0aGVudGljYXRpb24iLCAiandzIjogIiJ9fQ.IITX3UAy_S7WEoVWBXZwCsGoTt78KWu1_8Ccr8NLZFUYt-ETnRt7qNWDvB258DlRbraC9YPpRuhkkQPCJ4_2yQ"
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/docs/VC-DID-examples/VC-OEMproducedBMS.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vc.bmsProduction.schema.html"
  ],
  "id": "urn:uuid:982c43ee-3d16-419a-a2f4-5c61710f428b",
  "type": [
    "VerifiableCredential",
    "BMSProduction"
  ],
  "issuer": "did:batterypass:bms.sn-987654321",
  "holder": "did:batterypass:oem.VW",
  "issuanceDate": "2025-06-10T12:01:00Z",
  "expirationDate": "2026-06-10T12:01:00Z",
  "credentialSubject": {
    "id": "did:batterypass:oem.VW",
    "type": "BMSProduction",
    "bmsDid": "did:batterypass:bms.sn-987654321",
    "timestamp": "2025-06-10",
    "lotNumber": "LOT-775533"
  },
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-06-10T12:01:03Z",
    "verificationMethod": "did:batterypass:bms.sn-987654321#device-key",
    "proofPurpose": "authentication",
    "jws": "eyJhbGciOiJFUzI1NiJ9..BASE64_SIG"
  }
}
