=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/jsonschema/vp.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "vp.schema.json",
  "title": "Battery-Ecosystem Verifiable Presentation",
  "description": "Schema for verifying presentations of VCs with holder proof.",
  "type": "object",
  "required": [
    "@context",
    "type",
    "verifiableCredential",
    "holder",
    "proof"
  ],
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "enum": [
          "https://www.w3.org/2018/credentials/v1",
          "http://localhost:8443/docs/vp.schema.html"
        ]
      },
      "minItems": 2,
      "maxItems": 2,
      "uniqueItems": true,
      "description": "Defines the JSON-LD context, providing meaning to terms used in the credential."
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "contains": {
        "const": "VerifiablePresentation"
      },
      "description": "Type of the object, must include 'VerifiablePresentation'."
    },
    "verifiableCredential": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "$ref": "vc.schema.json"
      },
      "description": "Array of Verifiable Credentials being presented (only one allowed here)."
    },
    "holder": {
      "type": "string",
      "format": "uri",
      "description": "DID of the entity presenting the credentials."
    },
    "proof": {
      "title": "Proof",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "created",
        "verificationMethod",
        "challenge",
        "proofPurpose",
        "jws"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["EcdsaSecp256r1Signature2019"],
          "description": "Type of digital signature."
        },
        "created": {
          "type": "string",
          "format": "date-time",
          "description": "Time the proof was created."
        },
        "verificationMethod": {
          "type": "string",
          "pattern": "^did:[a-z0-9]+:[a-zA-Z0-9.\\-]+#[a-zA-Z0-9_-]+$",
          "description": "The DID that identifies the public key used to verify the signature. (Holder)"
        },
        "challenge": {
          "type": "string",
          "description": "A random string provided by the Verifier upon request to prevent replay attacks."
        },
        "proofPurpose": {
          "type": "string",
          "enum": ["authentication"],
          "description": "The purpose for which the proof is provided"
        },
        "jws": {
          "type": "string",
          "description": "Signature of the Verifiable Credential."
        }
      }
    }
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/api/web/jsonexample/requests/request.vp.verify.3.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vp.schema.html"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "http://localhost:8443/docs/vc.serviceAccess.schema.html"
      ],
      "id": "urn:uuid:a1fd774e-5300-4171-b778-e53cedb64823",
      "type": [
        "VerifiableCredential",
        "CloudInstance"
      ],
      "issuer": "did:batterypass:bms.sn-544b51e7",
      "holder": "did:batterypass:cloud.sn-cloud1",
      "issuanceDate": "2025-06-17T16:17:43Z",
      "expirationDate": "2026-06-17T16:17:43Z",
      "credentialSubject": {
        "id": "did:batterypass:cloud.sn-cloud1",
        "type": "CloudInstance",
        "cloudDid": "did:batterypass:cloud.sn-cloud1",
        "timestamp": "2026-06-17T16:17:43Z"
      },
      "proof": {
        "type": "EcdsaSecp256r1Signature2019",
        "created": "2025-06-17T16:17:43Z",
        "verificationMethod": "did:batterypass:bms.sn-544b51e7#key-1",
        "proofPurpose": "authentication",
        "jws": ""
      }
    }
  ],
  "holder": "did:batterypass:cloud.sn-cloud1",
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-08-01T09:00:00Z",
    "verificationMethod": "did:batterypass:cloud.sn-cloud1#key-1",
    "challenge": "c82f7883-42a1-4b78-9c2e-d8d5321af9f8",
    "proofPurpose": "authentication",
    "jws": ""
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/api/web/jsonexample/requests/request.vp.verify.1.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vp.schema.html"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "verifiableCredential": [
    {"@context": ["https://www.w3.org/2018/credentials/v1", "http://localhost:8443/docs/vc.bmsProduction.schema.html"], "id": "urn:uuid:982c43ee-3d16-419a-a2f4-5c61710f428b", "type": [
        "VerifiableCredential",
        "BMSProduction"], "issuer": "did:batterypass:bms.sn-544b51e7", "holder": "did:batterypass:oem.VW", "issuanceDate": "2025-06-10T12:01:00Z", "expirationDate": "2026-06-10T12:01:00Z", "credentialSubject": {"id": "did:batterypass:oem.VW", "type": "BMSProduction", "bmsDid": "did:batterypass:bms.sn-544b51e7", "timestamp": "2025-06-10T12:01:00Z", "lotNumber": "LOT-775533"}, "proof": {"type": "EcdsaSecp256r1Signature2019", "created": "2025-06-10T12:01:03Z", "verificationMethod": "did:batterypass:bms.sn-544b51e7#key-1", "proofPurpose": "authentication", "jws": "eyJhbGciOiJFUzI1NiJ9.eyJAY29udGV4dCI6IFsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCAiaHR0cDovL2xvY2FsaG9zdDo4NDQzL2RvY3MvdmMuYm1zUHJvZHVjdGlvbi5zY2hlbWEuaHRtbCJdLCAiaWQiOiAidXJuOnV1aWQ6OTgyYzQzZWUtM2QxNi00MTlhLWEyZjQtNWM2MTcxMGY0MjhiIiwgInR5cGUiOiBbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwgIkJNU1Byb2R1Y3Rpb24iXSwgImlzc3VlciI6ICJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnNuLTU0NGI1MWU3IiwgImhvbGRlciI6ICJkaWQ6YmF0dGVyeXBhc3M6b2VtLlZXIiwgImlzc3VhbmNlRGF0ZSI6ICIyMDI1LTA2LTEwVDEyOjAxOjAwWiIsICJleHBpcmF0aW9uRGF0ZSI6ICIyMDI2LTA2LTEwVDEyOjAxOjAwWiIsICJjcmVkZW50aWFsU3ViamVjdCI6IHsiaWQiOiAiZGlkOmJhdHRlcnlwYXNzOm9lbS5WVyIsICJ0eXBlIjogIkJNU1Byb2R1Y3Rpb24iLCAiYm1zRGlkIjogImRpZDpiYXR0ZXJ5cGFzczpibXMuc24tNTQ0YjUxZTciLCAidGltZXN0YW1wIjogIjIwMjUtMDYtMTBUMTI6MDE6MDBaIiwgImxvdE51bWJlciI6ICJMT1QtNzc1NTMzIn0sICJwcm9vZiI6IHsidHlwZSI6ICJFY2RzYVNlY3AyNTZyMVNpZ25hdHVyZTIwMTkiLCAiY3JlYXRlZCI6ICIyMDI1LTA2LTEwVDEyOjAxOjAzWiIsICJ2ZXJpZmljYXRpb25NZXRob2QiOiAiZGlkOmJhdHRlcnlwYXNzOmJtcy5zbi01NDRiNTFlNyNrZXktMSIsICJwcm9vZlB1cnBvc2UiOiAiYXV0aGVudGljYXRpb24iLCAiandzIjogIiJ9fQ.IITX3UAy_S7WEoVWBXZwCsGoTt78KWu1_8Ccr8NLZFUYt-ETnRt7qNWDvB258DlRbraC9YPpRuhkkQPCJ4_2yQ"}}
  ],
  "holder": "did:batterypass:service.sn-service1",
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-08-01T09:00:00Z",
    "verificationMethod": "did:batterypass:service.sn-service1#key-1",
    "challenge": "c82f7883-42a1-4b78-9c2e-d8d5321af9f8",
    "proofPurpose": "authentication",
    "jws": "eyJhbGciOiJFUzI1NiJ9.eyJAY29udGV4dCI6IFsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCAiaHR0cDovL2xvY2FsaG9zdDo4NDQzL2RvY3MvdnAuc2NoZW1hLmh0bWwiXSwgInR5cGUiOiBbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iXSwgInZlcmlmaWFibGVDcmVkZW50aWFsIjogW3siQGNvbnRleHQiOiBbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwgImh0dHA6Ly9sb2NhbGhvc3Q6ODQ0My9kb2NzL3ZjLmJtc1Byb2R1Y3Rpb24uc2NoZW1hLmh0bWwiXSwgImlkIjogInVybjp1dWlkOjk4MmM0M2VlLTNkMTYtNDE5YS1hMmY0LTVjNjE3MTBmNDI4YiIsICJ0eXBlIjogWyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsICJCTVNQcm9kdWN0aW9uIl0sICJpc3N1ZXIiOiAiZGlkOmJhdHRlcnlwYXNzOmJtcy5zbi01NDRiNTFlNyIsICJob2xkZXIiOiAiZGlkOmJhdHRlcnlwYXNzOm9lbS5WVyIsICJpc3N1YW5jZURhdGUiOiAiMjAyNS0wNi0xMFQxMjowMTowMFoiLCAiZXhwaXJhdGlvbkRhdGUiOiAiMjAyNi0wNi0xMFQxMjowMTowMFoiLCAiY3JlZGVudGlhbFN1YmplY3QiOiB7ImlkIjogImRpZDpiYXR0ZXJ5cGFzczpvZW0uVlciLCAidHlwZSI6ICJCTVNQcm9kdWN0aW9uIiwgImJtc0RpZCI6ICJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnNuLTU0NGI1MWU3IiwgInRpbWVzdGFtcCI6ICIyMDI1LTA2LTEwVDEyOjAxOjAwWiIsICJsb3ROdW1iZXIiOiAiTE9ULTc3NTUzMyJ9LCAicHJvb2YiOiB7InR5cGUiOiAiRWNkc2FTZWNwMjU2cjFTaWduYXR1cmUyMDE5IiwgImNyZWF0ZWQiOiAiMjAyNS0wNi0xMFQxMjowMTowM1oiLCAidmVyaWZpY2F0aW9uTWV0aG9kIjogImRpZDpiYXR0ZXJ5cGFzczpibXMuc24tNTQ0YjUxZTcja2V5LTEiLCAicHJvb2ZQdXJwb3NlIjogImF1dGhlbnRpY2F0aW9uIiwgImp3cyI6ICJleUpoYkdjaU9pSkZVekkxTmlKOS5leUpBWTI5dWRHVjRkQ0k2SUZzaWFIUjBjSE02THk5M2QzY3Vkek11YjNKbkx6SXdNVGd2WTNKbFpHVnVkR2xoYkhNdmRqRWlMQ0FpYUhSMGNEb3ZMMnh2WTJGc2FHOXpkRG80TkRRekwyUnZZM012ZG1NdVltMXpVSEp2WkhWamRHbHZiaTV6WTJobGJXRXVhSFJ0YkNKZExDQWlhV1FpT2lBaWRYSnVPblYxYVdRNk9UZ3lZelF6WldVdE0yUXhOaTAwTVRsaExXRXlaalF0TldNMk1UY3hNR1kwTWpoaUlpd2dJblI1Y0dVaU9pQmJJbFpsY21sbWFXRmliR1ZEY21Wa1pXNTBhV0ZzSWl3Z0lrSk5VMUJ5YjJSMVkzUnBiMjRpWFN3Z0ltbHpjM1ZsY2lJNklDSmthV1E2WW1GMGRHVnllWEJoYzNNNlltMXpMbk51TFRVME5HSTFNV1UzSWl3Z0ltaHZiR1JsY2lJNklDSmthV1E2WW1GMGRHVnllWEJoYzNNNmIyVnRMbFpYSWl3Z0ltbHpjM1ZoYm1ObFJHRjBaU0k2SUNJeU1ESTFMVEEyTFRFd1ZERXlPakF4T2pBd1dpSXNJQ0psZUhCcGNtRjBhVzl1UkdGMFpTSTZJQ0l5TURJMkxUQTJMVEV3VkRFeU9qQXhPakF3V2lJc0lDSmpjbVZrWlc1MGFXRnNVM1ZpYW1WamRDSTZJSHNpYVdRaU9pQWlaR2xrT21KaGRIUmxjbmx3WVhOek9tOWxiUzVXVnlJc0lDSjBlWEJsSWpvZ0lrSk5VMUJ5YjJSMVkzUnBiMjRpTENBaVltMXpSR2xrSWpvZ0ltUnBaRHBpWVhSMFpYSjVjR0Z6Y3pwaWJYTXVjMjR0TlRRMFlqVXhaVGNpTENBaWRHbHRaWE4wWVcxd0lqb2dJakl3TWpVdE1EWXRNVEJVTVRJNk1ERTZNREJhSWl3Z0lteHZkRTUxYldKbGNpSTZJQ0pNVDFRdE56YzFOVE16SW4wc0lDSndjbTl2WmlJNklIc2lkSGx3WlNJNklDSkZZMlJ6WVZObFkzQXlOVFp5TVZOcFoyNWhkSFZ5WlRJd01Ua2lMQ0FpWTNKbFlYUmxaQ0k2SUNJeU1ESTFMVEEyTFRFd1ZERXlPakF4T2pBeldpSXNJQ0oyWlhKcFptbGpZWFJwYjI1TlpYUm9iMlFpT2lBaVpHbGtPbUpoZEhSbGNubHdZWE56T21KdGN5NXpiaTAxTkRSaU5URmxOeU5yWlhrdE1TSXNJQ0p3Y205dlpsQjFjbkJ2YzJVaU9pQWlZWFYwYUdWdWRHbGpZWFJwYjI0aUxDQWlhbmR6SWpvZ0lpSjlmUS5JSVRYM1VBeV9TN1dFb1ZXQlhad0NzR29UdDc4S1d1MV84Q2NyOE5MWkZVWXQtRVRuUnQ3cU5XRHZCMjU4RGxSYnJhQzlZUHBSdWhra1FQQ0o0XzJ5USJ9fV0sICJob2xkZXIiOiAiZGlkOmJhdHRlcnlwYXNzOnNlcnZpY2Uuc24tc2VydmljZTEiLCAicHJvb2YiOiB7InR5cGUiOiAiRWNkc2FTZWNwMjU2cjFTaWduYXR1cmUyMDE5IiwgImNyZWF0ZWQiOiAiMjAyNS0wOC0wMVQwOTowMDowMFoiLCAidmVyaWZpY2F0aW9uTWV0aG9kIjogImRpZDpiYXR0ZXJ5cGFzczpzZXJ2aWNlLnNuLXNlcnZpY2UxI2tleS0xIiwgImNoYWxsZW5nZSI6ICJjODJmNzg4My00MmExLTRiNzgtOWMyZS1kOGQ1MzIxYWY5ZjgiLCAicHJvb2ZQdXJwb3NlIjogImF1dGhlbnRpY2F0aW9uIiwgImp3cyI6ICIifX0.iDR9UBIYyx-u9VRg5Bb4003ZfHKfmDspJElvSPVAGtg2MGnPp83gzOEd03tvUunflaCYSXBx0iDdNuCsAQN1Hg"
  }
}

=== THI-CSI/decentralized_iam_battery_data/blockchain/internal/api/web/jsonexample/requests/request.vp.verify.2.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "http://localhost:8443/docs/vp.schema.html"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "http://localhost:8443/docs/vc.serviceAccess.schema.html"
      ],
      "id": "urn:uuid:a1fd774e-5300-4171-b778-e53cedb64823",
      "type": [
        "VerifiableCredential",
        "ServiceAccess"
      ],
      "issuer": "did:batterypass:bms.sn-544b51e7",
      "holder": "did:batterypass:service.sn-service1",
      "issuanceDate": "2025-06-17T16:17:43Z",
      "expirationDate": "2026-06-17T16:17:43Z",
      "credentialSubject": {
        "id": "did:batterypass:service.sn-service1",
        "type": "ServiceAccess",
        "bmsDid": "did:batterypass:bms.sn-544b51e7",
        "accessLevel": [
          "read",
          "write"
        ],
        "validFrom": "2025-06-17T16:17:43Z",
        "validUntil": "2026-06-17T16:17:43Z"
      },
      "proof": {
        "type": "EcdsaSecp256r1Signature2019",
        "created": "2025-06-17T16:17:43Z",
        "verificationMethod": "did:batterypass:bms.sn-544b51e7#key-1",
        "proofPurpose": "authentication",
        "jws": "eyJhbGciOiJFUzI1NiJ9.eyJAY29udGV4dCI6IFsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCAiaHR0cDovL2xvY2FsaG9zdDo4NDQzL2RvY3MvdmMuc2VydmljZUFjY2Vzcy5zY2hlbWEuaHRtbCJdLCAiaWQiOiAidXJuOnV1aWQ6YTFmZDc3NGUtNTMwMC00MTcxLWI3NzgtZTUzY2VkYjY0ODIzIiwgInR5cGUiOiBbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwgIlNlcnZpY2VBY2Nlc3MiXSwgImlzc3VlciI6ICJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnNuLTU0NGI1MWU3IiwgImhvbGRlciI6ICJkaWQ6YmF0dGVyeXBhc3M6c2VydmljZS5zbi1zZXJ2aWNlMSIsICJpc3N1YW5jZURhdGUiOiAiMjAyNS0wNi0xN1QxNjoxNzo0M1oiLCAiZXhwaXJhdGlvbkRhdGUiOiAiMjAyNi0wNi0xN1QxNjoxNzo0M1oiLCAiY3JlZGVudGlhbFN1YmplY3QiOiB7ImlkIjogImRpZDpiYXR0ZXJ5cGFzczpzZXJ2aWNlLnNuLXNlcnZpY2UxIiwgInR5cGUiOiAiU2VydmljZUFjY2VzcyIsICJibXNEaWQiOiAiZGlkOmJhdHRlcnlwYXNzOmJtcy5zbi01NDRiNTFlNyIsICJhY2Nlc3NMZXZlbCI6IFsicmVhZCIsICJ3cml0ZSJdLCAidmFsaWRGcm9tIjogIjIwMjUtMDYtMTdUMTY6MTc6NDNaIiwgInZhbGlkVW50aWwiOiAiMjAyNi0wNi0xN1QxNjoxNzo0M1oifSwgInByb29mIjogeyJ0eXBlIjogIkVjZHNhU2VjcDI1NnIxU2lnbmF0dXJlMjAxOSIsICJjcmVhdGVkIjogIjIwMjUtMDYtMTdUMTY6MTc6NDNaIiwgInZlcmlmaWNhdGlvbk1ldGhvZCI6ICJkaWQ6YmF0dGVyeXBhc3M6Ym1zLnNuLTU0NGI1MWU3I2tleS0xIiwgInByb29mUHVycG9zZSI6ICJhdXRoZW50aWNhdGlvbiIsICJqd3MiOiAiIn19.dRN5eT2z_RGjJOT4Mq29vMOXLH5LBFfrcHUwwjf_dh_vassHwccT-kTwSlecGgKhd0GIOVQvHVPR88zYnqzpcQ"
      }
    }
  ],
  "holder": "did:batterypass:oem.sn-audi",
  "proof": {
    "type": "EcdsaSecp256r1Signature2019",
    "created": "2025-08-01T09:00:00Z",
    "verificationMethod": "did:batterypass:service.sn-service1#key-1",
    "challenge": "c82f7883-42a1-4b78-9c2e-d8d5321af9f8",
    "proofPurpose": "authentication",
    "jws": ""
  }
}
